modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="mixy"
version="${version}"
displayName="Mixy"
displayTest = "IGNORE_SERVER_VERSION"
#logoFile="assets/voxy/icon.png"
authors="Cortex, Ferri_Arnus"
description='''
Far distance rendering mod utilising LoDs
'''

[[dependencies.voxy]]
modId = "neoforge"
type="required"
versionRange = "[20.4.40-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voxy]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voxy]]
modId = "embeddium"
type="required"
versionRange = "[0.2.2+mc1.20.4, )"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "voxy.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="voxy"
displayName="Voxy (Mixy)"
version="${version}"
authors="Cortex"
logoFile="assets/voxy/icon.png"
description='''
Far distance rendering mod utilising LoDs
'''